config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists, only: [:index, :show, :new, :create ]
  resources :movies, only: [:index, :show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates_length_of :comment, minimum: 6
  validates_uniqueness_of :movie_id, scope: :list_id
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, :overview, presence: true, uniqueness: true
  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save

    redirect_to list_path(@list.id)
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies = Movie.all
  end

  def show
    # @movie = Movie.all
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    @movie.save

    redirect_to movie_path(@movie)
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :overview, :poster_url, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_listmovie.html.erb
<div class="list-card">
  <h3><%= link_to list.name, list_path(list.id)%></h3>
</div>

app/views/lists/index.html.erb
<h1 class="mt-3">My lists</h1>

<% @lists.each do |list| %>
<%= render "listmovie", list: list %>
<% end %>
<div class="btn btn-dark" ><%= link_to 'Create new List', new_list_path%></div>

app/views/lists/new.html.erb
<%= simple_form_for(@list) do |l| %>
  <%= l.input :name %>
  <%= l.submit %>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

app/views/movies/_allmovies.html.erb
<div class="moviecard">
<h5><%=movie.title%></h5>
<%= link_to 'See More', movie_path(movie) %>
</div>

app/views/movies/index.html.erb
<h1 class="mt-3">All movies</h1>
<%= link_to 'Add Movie', new_movie_path %>
<div class="grid">
<% @movies.each do |movie| %>
<%= render "allmovies", movie: movie %>
<% end %>
</div>

app/views/movies/new.html.erb
<%= simple_form_for(@movie) do |m| %>
  <%= m.input :title, placeholder: 'Enter title of movie'%>
  <%= m.input :overview, placeholder: 'Make a description' %>
  <%= m.input :poster_url%>
  <%= m.input :rating %>
  <%= m.submit %>
<% end %>

app/views/movies/show.html.erb
<h3><%= @movie.title %></h3>
<p><%= @movie.overview %></p>
<strong>Rating: <%= @movie.rating %></strong>
<%= image_tag @movie.poster_url %>